To connect to the notebook type the following command into your local terminal:
ssh -N -J tpelletreaudur@int4-pub.snellius.surf.nl tpelletreaudur@gcn17.local.snellius.surf.nl -L 5634:localhost:5634

After connection is established in your local browser go to the address:
http://localhost:5634
[I 16:53:58.026 NotebookApp] Serving notebooks from local directory: /gpfs/home3/tpelletreaudur/Probing-GNN-representations
[I 16:53:58.026 NotebookApp] Jupyter Notebook 6.4.0 is running at:
[I 16:53:58.026 NotebookApp] http://localhost:5634/?token=28b05fda4203f8653e286039dd656aaf574832694f8db0a0
[I 16:53:58.026 NotebookApp]  or http://127.0.0.1:5634/?token=28b05fda4203f8653e286039dd656aaf574832694f8db0a0
[I 16:53:58.026 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:53:58.035 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///gpfs/home3/tpelletreaudur/.local/share/jupyter/runtime/nbserver-2137716-open.html
    Or copy and paste one of these URLs:
        http://localhost:5634/?token=28b05fda4203f8653e286039dd656aaf574832694f8db0a0
     or http://127.0.0.1:5634/?token=28b05fda4203f8653e286039dd656aaf574832694f8db0a0
[I 16:57:09.110 NotebookApp] 302 GET /?token=28b05fda4203f8653e286039dd656aaf574832694f8db0a0 (::1) 0.450000ms
/sw/arch/RHEL8/EB_production/2022/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[W 16:57:34.392 NotebookApp] Notebook Probing_GCN.ipynb is not trusted
Exception in callback Task.task_wakeup(<Future finis...c: 1\r\n\r\n'>)
handle: <Handle Task.task_wakeup(<Future finis...c: 1\r\n\r\n'>)>
Traceback (most recent call last):
  File "/sw/arch/RHEL8/EB_production/2022/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-6' coro=<HTTP1ServerConnection._server_request_loop() running at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/tornado/http1connection.py:825> wait_for=<Future finished result=b'GET /api/co...pc: 1\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/tornado/ioloop.py:687]> while another task <Task pending name='Task-2' coro=<KernelManager._async_start_kernel() running at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/jupyter_client/manager.py:75>> is being executed.
Exception in callback Task.task_wakeup(<Future finis...c: 1\r\n\r\n'>)
handle: <Handle Task.task_wakeup(<Future finis...c: 1\r\n\r\n'>)>
Traceback (most recent call last):
  File "/sw/arch/RHEL8/EB_production/2022/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-13' coro=<HTTP1ServerConnection._server_request_loop() running at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/tornado/http1connection.py:825> wait_for=<Future finished result=b'GET /kernel...pc: 1\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/tornado/ioloop.py:687]> while another task <Task pending name='Task-2' coro=<KernelManager._async_start_kernel() running at /sw/arch/RHEL8/EB_production/2022/software/IPython/8.5.0-GCCcore-11.3.0/lib/python3.10/site-packages/jupyter_client/manager.py:75>> is being executed.
[I 16:57:35.533 NotebookApp] Kernel started: 5789987f-0806-4abb-8db5-e63f5adfe162, name: python3
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: 37ea0fd6-f771-4823-8dce-1674dd09690a
[I 16:59:35.743 NotebookApp] Saving file at /Probing_GCN.ipynb
[W 16:59:35.745 NotebookApp] Notebook Probing_GCN.ipynb is not trusted
[I 17:01:50.808 NotebookApp] Kernel interrupted: 5789987f-0806-4abb-8db5-e63f5adfe162
[I 17:03:35.733 NotebookApp] Saving file at /Probing_GCN.ipynb
[W 17:03:35.734 NotebookApp] Notebook Probing_GCN.ipynb is not trusted
[I 17:03:48.774 NotebookApp] Kernel interrupted: 5789987f-0806-4abb-8db5-e63f5adfe162
[I 17:04:14.889 NotebookApp] Saving file at /models/models_BA_2grid_house.py
[I 17:04:19.499 NotebookApp] Starting buffering for 5789987f-0806-4abb-8db5-e63f5adfe162:14defb1b9240433383d33de21185da49
[I 17:04:20.433 NotebookApp] Kernel restarted: 5789987f-0806-4abb-8db5-e63f5adfe162
[I 17:04:20.450 NotebookApp] Restoring connection for 5789987f-0806-4abb-8db5-e63f5adfe162:14defb1b9240433383d33de21185da49
[I 17:04:21.337 NotebookApp] Replaying 3 buffered messages
[I 17:05:35.750 NotebookApp] Saving file at /Probing_GCN.ipynb
[W 17:05:35.751 NotebookApp] Notebook Probing_GCN.ipynb is not trusted
[I 17:07:35.915 NotebookApp] Saving file at /Probing_GCN.ipynb
[W 17:07:35.915 NotebookApp] Notebook Probing_GCN.ipynb is not trusted
[I 17:07:40.046 NotebookApp] Saving file at /models/models_BA_2grid_house.py
[I 17:07:45.873 NotebookApp] Kernel interrupted: 5789987f-0806-4abb-8db5-e63f5adfe162
[I 17:07:48.481 NotebookApp] Starting buffering for 5789987f-0806-4abb-8db5-e63f5adfe162:14defb1b9240433383d33de21185da49
[I 17:07:49.413 NotebookApp] Kernel restarted: 5789987f-0806-4abb-8db5-e63f5adfe162
[I 17:07:49.431 NotebookApp] Restoring connection for 5789987f-0806-4abb-8db5-e63f5adfe162:14defb1b9240433383d33de21185da49
[I 17:07:50.436 NotebookApp] Replaying 3 buffered messages
[I 17:09:35.798 NotebookApp] Saving file at /Probing_GCN.ipynb
[W 17:09:35.799 NotebookApp] Notebook Probing_GCN.ipynb is not trusted
[I 17:11:35.804 NotebookApp] Saving file at /Probing_GCN.ipynb
[W 17:11:35.805 NotebookApp] Notebook Probing_GCN.ipynb is not trusted
[I 17:13:35.784 NotebookApp] Saving file at /Probing_GCN.ipynb
[W 17:13:35.785 NotebookApp] Notebook Probing_GCN.ipynb is not trusted
[I 17:15:35.760 NotebookApp] Saving file at /Probing_GCN.ipynb
[W 17:15:35.761 NotebookApp] Notebook Probing_GCN.ipynb is not trusted
[I 17:17:35.821 NotebookApp] Saving file at /Probing_GCN.ipynb
[W 17:17:35.822 NotebookApp] Notebook Probing_GCN.ipynb is not trusted
[I 17:19:35.798 NotebookApp] Saving file at /Probing_GCN.ipynb
[W 17:19:35.799 NotebookApp] Notebook Probing_GCN.ipynb is not trusted
[I 17:22:21.999 NotebookApp] Saving file at /Probing_GCN.ipynb
[W 17:22:22.000 NotebookApp] Notebook Probing_GCN.ipynb is not trusted
[I 17:24:21.948 NotebookApp] Saving file at /Probing_GCN.ipynb
[W 17:24:21.949 NotebookApp] Notebook Probing_GCN.ipynb is not trusted
[I 17:25:35.944 NotebookApp] Saving file at /Probing_GCN.ipynb
[W 17:25:35.945 NotebookApp] Notebook Probing_GCN.ipynb is not trusted
[I 17:28:21.970 NotebookApp] Saving file at /Probing_GCN.ipynb
[W 17:28:21.971 NotebookApp] Notebook Probing_GCN.ipynb is not trusted
[I 17:29:35.919 NotebookApp] Saving file at /Probing_GCN.ipynb
[W 17:29:35.920 NotebookApp] Notebook Probing_GCN.ipynb is not trusted
[I 17:32:19.921 NotebookApp] Saving file at /Probing_GCN.ipynb
[W 17:32:19.922 NotebookApp] Notebook Probing_GCN.ipynb is not trusted
[I 17:33:35.813 NotebookApp] Saving file at /Probing_GCN.ipynb
[W 17:33:35.814 NotebookApp] Notebook Probing_GCN.ipynb is not trusted
[I 17:34:26.594 NotebookApp] Starting buffering for 5789987f-0806-4abb-8db5-e63f5adfe162:14defb1b9240433383d33de21185da49
